title: "Botgame.io"
description: "AI-generated insights about gaming, esports, and automation."
baseurl: ""
url: "https://botgame.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
