name: Auto Generate Daily AI Post
on:
  schedule:
    - cron: '0 9 * * *'   # 09:00 UTC (~16:00 VN)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
      - name: Run generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python auto_generate.py
      - name: Commit posts
        run: |
          git config user.name "Auto Bot"
          git config user.email "auto@users.noreply.github.com"
          git add _posts || true
          if git diff --cached --quiet; then
            echo "No new posts";
          else
            git commit -m "📰 Auto post $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push
          fi
      - name: Ping Google
        run: |
          curl -s "https://www.google.com/ping?sitemap=https://botgame.io/sitemap.xml" || true
